version: '3'
services:
  distbot-dev-ff:
    volumes:
    - /rn/distbot:/tests
    network_mode: "host"
    image: distbot
    command: -e dev -b headlessfirefox -u lll -p kkk --mode distributed --max-cpu-percent 80 --max-memory 1024 examples
    